version: '3'
services:
  proxy:
    build: ./nginx
    image: docker-dash-encoder:nginx
    volumes:
    - './nginx/static.conf:/etc/nginx/conf.d/default.conf'
    - './media:/media'
    ports:
    - "8000:80"
