version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: docker-dash-encoder:nginx
    volumes:
    - './static.conf:/etc/nginx/conf.d/default.conf'
    - './media:/media'
    ports:
    - "8000:80"
